### ISSUE TITLE
Not optimized for SRP compatibility

### ISSUE THREAD

**Issue by kraj0t** [lukakldiashvili/Unified-Renderer-Unity#1]
As it is right now, the `UnifiedRenderer` component forces a dedicated drawcall for each `Renderer` it's attached to.

Proposal: in order to make the `UnifiedRenderer` compatible with the SRP batcher, the code should modify the `sharedMaterials` directly, without using `MaterialPropertyBlocks`.

More info in the official doc for the [SRP batcher](https://docs.unity3d.com/Manual/SRPBatcher.html).

**Comment by lukakldiashvili** [comment]
@kraj0t  That is correct, but MaterialPropertyBlock is the foundation that allows to modify how each object renders without separate materials (at least in UnifiedRenderer).

Modifying sharedMaterials will affect other objects that are using the same material, which defeats the purpose.
Another way would be to automatically create and manage new instances/clones of original material, but it may hinder editor experience.

Could you elaborate more about the specifics of your proposal?
